version: '3.8'

services:
  fastapi-app:
    container_name: twc3teslafi-simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8667"
    environment:
      TESLAFI_API_KEY: "XXX_YOUR_TESLAFI_API_KEY_XXX"
      LONGITUDE: "48.201773" #charger location longitude
      LATITUDE: "16.348655" #charger locatoin latitude
      RADIUS: "200" #geofence radius in meters
    restart: always