version: '3.8'

services:
  fastapi-app:
    container_name: twc3teslafi-simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8667"
    environment:
      - TESLAFI_API_KEY=XXX_YOUR_API_KEY_XXXX
    restart: always
